server:
  port: 5349
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/your_db
    username: your_username
    password: your_password
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
